BluePsyduck\FactorioModPortalClient\Entity\InfoJson:
  access_type: public_method
  exclusion_policy: all
  properties:
    dependencies:
      type: array<dependency>
      serialized_name: dependencies
    factorioVersion:
      type: version
      serialized_name: factorio_version
