BluePsyduck\FactorioModPortalClient\Response\ModListResponse:
  access_type: public_method
  exclusion_policy: all
  properties:
    pagination:
      type: BluePsyduck\FactorioModPortalClient\Entity\Pagination
      serialized_name: pagination
    results:
      type: array<BluePsyduck\FactorioModPortalClient\Entity\Mod>
      serialized_name: results
